services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: node server.js

  frontend:
    build:
      context: ./smart-home-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
